### ISSUE TITLE
Missing "rev" field in the configuration

### ISSUE THREAD

**Issue by avsej** [couchbaselabs/gocaves#1]
I need to implement this part in ruby client (but it would be nice that CAVES support both modes to make sure SDK works with optional `"rev"`)

https://github.com/couchbase/gocbcore/blob/603f81fa25ea0d87572beb5754ec9605eadb9990/configmanagement_component.go#L123-L136

```go
// Check that the new config data is newer than the current one, in the case where we've done a select bucket
// against an existing connection then the revisions could be the same. In that case the configuration still
// needs to be applied.
if cfg.revID == 0 {
    logDebugf("Unversioned configuration data, switching.")
} else if cfg.bktType != oldCfg.bktType {
    logDebugf("Configuration data changed bucket type, switching.")
} else if cfg.revID == oldCfg.revID {
    logDebugf("Ignoring configuration with identical revision number")
    return false
} else if cfg.revID < oldCfg.revID {
    logDebugf("Ignoring new configuration as it has an older revision id")
    return false
}
```

**Comment by avsej** [comment]
Also, it looks like CCCP implementation not always uses "terse" configuration.
https://github.com/couchbaselabs/gocaves/blob/eb9658a6f6b684d0b91b0b3e118a6742ec84a787/mock/mockimpl/svcimpls/kvimplcccp.go#L18-L23

While it seems like at least modern ns_server always uses terse configuration

**Comment by chvck** [comment]
I believe this is now fixed.
