### ISSUE TITLE
caves does not implement hello?

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/gocaves#35]
A java kv integration test fails on something (simplified):

```java
    MutationResult insertResult = collection.insert(id, "Hello, World");
    assertTrue(insertResult.mutationToken().isPresent());
```

Looks like mutation tokens are not yet implemented for caves?

**Comment by daschl** [comment]
Naturally, this makes all persistTo/replicateTo tests fail as well.

**Comment by brett19** [comment]
It appears the real cause here is that the mock does not reply with the actual list of supported features.

**Comment by daschl** [comment]
passing now.
